---
- name: Restart Nginx on AWS EC2 instances
  hosts: 98.81.122.109
  become: true
  tasks:
    - name: Restart Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
