---
- name: Restart Nginx on AWS EC2 instances
  hosts: 
    - ubuntu@ec2-54-164-99-156.compute-1.amazonaws.com
  become: true
  tasks:
    - name: Restart Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
