---
- name: Restart Nginx on AWS EC2 instances
  hosts: 
     - ec2-98-81-122-109.compute-1.amazonaws.com
  user: ubuntu
  become: true
  tasks:
    - name: Stop Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: stopped
