---
- name: Restart Nginx on AWS EC2 instances
  hosts: all
  user: ubuntu
  become: true
  tasks:
    - name: Start Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: started
