---
- name: Restart Nginx on AWS EC2 instances
  hosts: public_dns_name
  user: ubuntu
  become: true
  tasks:
    - name: Stop Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: stopped
