---
- name: Restart Nginx on AWS EC2 instances
  hosts: all
  user: ubuntu
  become: true
  tasks:
    - name: Stop Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: stopped
    - name: Start Nginx Service
      ansible.builtin.systemd:
         name: nginx
         state: started

    - name: create a directory
      ansible.builtin.file:
      path: /opt/dev
      owner: ubuntu
      group: ubuntu
      state: directory
      
